RANDOM_SEED: 0
FP16_OPT: 2

DATA:
  ROOT: datasets/coco
  TOKENIZER_VOCAB: "datasets/vocab/coco_10k.vocab"
  TOKENIZER_MODEL: "datasets/vocab/coco_10k.model"

  IMAGE_CROP_SIZE: 224
  MAX_CAPTION_LENGTH: 30

  IMAGE_TRANSFORM_TRAIN:
    - random_resized_crop
    - horizontal_flip
    - color_jitter
    - normalize

  IMAGE_TRANSFORM_VAL:
    - smallest_resize
    - center_crop
    - normalize

  USE_PERCENTAGE: 100.0
  USE_SINGLE_CAPTION: False

MODEL:
  NAME: bicaptioning
  VISUAL:
    NAME: torchvision::resnet50
    PRETRAINED: false
  TEXTUAL:
    NAME: transformer_postnorm::L1_H1024_A16_F4096
    HIDDEN_SIZE: 1024
    ATTENTION_HEADS: 16
    FEEDFORWARD_SIZE: 4096
    NUM_LAYERS: 1
  DROPOUT: 0.1

OPTIM:
  NUM_ITERATIONS: 1000000
  OPTIMIZER_NAME: sgd
  SGD_MOMENTUM: 0.9
  USE_LOOKAHEAD: True

  BATCH_SIZE: 256
  WEIGHT_DECAY: 1e-4
  LR: 0.001
  CNN_LR: 0.2
  LR_DECAY_NAME: cosine
  WARMUP_STEPS: 10000
  CLIP_GRAD_NORM: 10
